package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"secure_secrets/internal/backup"
	"secure_secrets/internal/biometrics"
	"secure_secrets/internal/config"
	"secure_secrets/internal/crypto"
	"secure_secrets/internal/daemon"
	"secure_secrets/internal/keychain"
	"secure_secrets/internal/store"
	"strings"
	"syscall"
	"time"

	"golang.org/x/term"
)

func pathToEnvKey(path string) string {
	s := strings.ToUpper(path)
	s = strings.ReplaceAll(s, "/", "_")
	s = strings.ReplaceAll(s, "-", "_")
	var buf bytes.Buffer
	for _, r := range s {
		if (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			buf.WriteRune(r)
		}
	}
	return buf.String()
}

func pathToEnvKeyWithEntry(path string, entry store.SecretEntry) string {
	if entry.Metadata != nil {
		if alias, ok := entry.Metadata["env_alias"]; ok && strings.TrimSpace(alias) != "" {
			return strings.TrimSpace(alias)
		}
	}
	return pathToEnvKey(path)
}

func handleImport(profile string, file string, args []string) {
	format := "json"
	prefix := ""

	for i := 0; i < len(args); i++ {
		if args[i] == "--format" || args[i] == "-f" {
			if i+1 < len(args) {
				format = strings.ToLower(args[i+1])
				i++
			}
		} else if args[i] == "--prefix" || args[i] == "-p" {
			if i+1 < len(args) {
				prefix = args[i+1]
				i++
			}
		}
	}

	// #nosec G304 G703
	data, err := os.ReadFile(file)
	if err != nil {
		fail("FILE_READ_ERROR", fmt.Errorf("failed to read import file %s: %v", file, err), "Check file path.")
	}

	pairs := make(map[string]string)
	if format == "json" || format == "doppler" || format == "aws" {
		var raw map[string]interface{}
		if err := json.Unmarshal(data, &raw); err != nil {
			fail("JSON_PARSE_ERROR", fmt.Errorf("failed to parse JSON file: %v", err), "Verify JSON syntax.")
		}
		for k, v := range raw {
			if strVal, ok := v.(string); ok {
				pairs[k] = strVal
			} else {
				pairs[k] = fmt.Sprintf("%v", v)
			}
		}
	} else {
		fail("UNSUPPORTED_FORMAT", fmt.Errorf("unsupported import format %q", format), "Use --format json|doppler|aws")
	}

	if prefix != "" && !strings.HasSuffix(prefix, "/") {
		prefix += "/"
	}

	importedCount := 0
	for k, valStr := range pairs {
		targetPath := prefix + k
		resp, err := queryDaemon(profile, daemon.IPCRequest{
			Action: "set",
			Path:   targetPath,
			Value:  valStr,
		})
		if err == nil && resp.Success {
			importedCount++
		}
	}

	fmt.Printf("Successfully imported %d secrets into profile %q.\n", importedCount, profile)
}

func handleExport(profile string, args []string) {
	format := "json"
	allProfiles := false
	envelope := true
	for i := 0; i < len(args); i++ {
		if args[i] == "--format" || args[i] == "-f" {
			if i+1 < len(args) {
				format = args[i+1]
				i++
			} else {
				fail("INVALID_ARGUMENT", fmt.Errorf("flag --format requires a value"), "Supported formats: json, env, aws, doppler, template")
			}
		} else if args[i] == "--all-profiles" {
			allProfiles = true
		} else if args[i] == "--no-envelope" {
			envelope = false
		} else if args[i] == "--envelope" {
			envelope = true
		}
	}
	if format != "env" && format != "json" && format != "aws" && format != "doppler" && format != "template" {
		fail("INVALID_ARGUMENT", fmt.Errorf("invalid format %q", format), "Supported formats: json, env, aws, doppler, template")
	}

	resp, err := queryDaemon(profile, daemon.IPCRequest{Action: "backup"})
	if err != nil {
		fail("DAEMON_NOT_RUNNING", fmt.Errorf("Daemon is not running. Please run 'sec open' to unlock the session."), "Run 'eval $(sec open)' to start/unlock the session.")
	}
	if !resp.Success {
		code, rem := mapDaemonError(resp.Error)
		fail(code, fmt.Errorf("%s", resp.Error), rem)
	}

	switch format {
	case "env":
		for path, entry := range resp.Secrets {
			envKey := pathToEnvKeyWithEntry(path, entry)
			fmt.Printf("%s=%q\n", envKey, entry.Value)
		}
	case "template":
		fmt.Printf("# Generated by sec-agent on %s\n", time.Now().Format("2006-01-02"))
		for path, entry := range resp.Secrets {
			envKey := pathToEnvKeyWithEntry(path, entry)
			fmt.Printf("%s=\"<migrated_to_sec>\"\n", envKey)
		}
	case "aws":
		type AWSSecret struct {
			SecretId     string `json:"SecretId"`
			SecretString string `json:"SecretString"`
		}
		var list []AWSSecret
		for path, entry := range resp.Secrets {
			list = append(list, AWSSecret{
				SecretId:     path,
				SecretString: entry.Value,
			})
		}
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		if err := enc.Encode(list); err != nil {
			fail("SERIALIZATION_FAILED", err, "")
		}
	case "doppler":
		flat := make(map[string]string)
		for path, entry := range resp.Secrets {
			flat[pathToEnvKeyWithEntry(path, entry)] = entry.Value
		}
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		if err := enc.Encode(flat); err != nil {
			fail("SERIALIZATION_FAILED", err, "")
		}
	default: // json
		storePath, _ := store.GetStorePath(profile)
		dbFile := filepath.Base(storePath)
		secenvFile := findWorkspaceConfigFile()
		if profile == "" {
			profile = "default"
		}

		if allProfiles {
			type ProfilePayload struct {
				DatabaseFile string                      `json:"database_file"`
				Secrets      map[string]store.SecretEntry `json:"secrets"`
			}
			exportAll := struct {
				Version    string                    `json:"version"`
				SecenvFile string                    `json:"secenv_file,omitempty"`
				ExportedAt time.Time                 `json:"exported_at"`
				Profiles   map[string]ProfilePayload `json:"profiles"`
			}{
				Version:    "1.0",
				SecenvFile: secenvFile,
				ExportedAt: time.Now(),
				Profiles:   make(map[string]ProfilePayload),
			}
			exportAll.Profiles[profile] = ProfilePayload{
				DatabaseFile: dbFile,
				Secrets:      resp.Secrets,
			}
			enc := json.NewEncoder(os.Stdout)
			enc.SetIndent("", "  ")
			if err := enc.Encode(exportAll); err != nil {
				fail("SERIALIZATION_FAILED", err, "")
			}
		} else if envelope {
			exportPackage := struct {
				Profile      string                      `json:"profile"`
				DatabaseFile string                      `json:"database_file"`
				SecenvFile   string                      `json:"secenv_file,omitempty"`
				ExportedAt   time.Time                   `json:"exported_at"`
				Secrets      map[string]store.SecretEntry `json:"secrets"`
			}{
				Profile:      profile,
				DatabaseFile: dbFile,
				SecenvFile:   secenvFile,
				ExportedAt:   time.Now(),
				Secrets:      resp.Secrets,
			}
			enc := json.NewEncoder(os.Stdout)
			enc.SetIndent("", "  ")
			if err := enc.Encode(exportPackage); err != nil {
				fail("SERIALIZATION_FAILED", err, "")
			}
		} else {
			enc := json.NewEncoder(os.Stdout)
			enc.SetIndent("", "  ")
			if err := enc.Encode(resp.Secrets); err != nil {
				fail("SERIALIZATION_FAILED", err, "")
			}
		}
	}
}

func handleBackup(profile string, outputFile string, explicitPassword string) {
	resp, err := queryDaemon(profile, daemon.IPCRequest{Action: "backup"})
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error: Daemon is not running. Please run 'sec open' to unlock the session.")
		os.Exit(1)
	}

	if !resp.Success {
		fmt.Fprintf(os.Stderr, "Error: %s\n", resp.Error)
		os.Exit(1)
	}

	if len(resp.Secrets) == 0 {
		fmt.Println("No secrets in the session cache to back up.")
		return
	}

	storeSecrets := make(map[store.SecretKey]store.SecretEntry)
	for k, v := range resp.Secrets {
		storeSecrets[store.SecretKey(k)] = store.SecretEntry{
			Value:        v.Value,
			Comment:      v.Comment,
			Metadata:     v.Metadata,
			Created:      v.Created,
			LastModified: v.LastModified,
			Expires:      v.Expires,
			Version:      v.Version,
			LastAccessed: v.LastAccessed,
			AccessCount:  v.AccessCount,
		}
	}

	var backupPassword string
	if explicitPassword != "" {
		backupPassword = explicitPassword
	} else {
		cfgDir, cfgErr := config.GetConfigDir()
		if cfgErr == nil {
			vaultPath := store.GetStorePathForProfile(profile)
			if store.IsV2Vault(vaultPath) {
				env, readErr := store.ReadVaultEnvelope(vaultPath)
				if readErr == nil && env.Slot1 != nil {
					if !isInteractiveTerminal() {
						fmt.Fprintln(os.Stderr, "⚠️  Non-interactive session detected.")
						fmt.Fprintln(os.Stderr, "Backup with BIP39 password requires an interactive terminal.")
						fmt.Fprintln(os.Stderr, "Use --custom-password to provide a password non-interactively.")
						os.Exit(1)
					}
					fmt.Println("📖 Enter your 24-word recovery mnemonic to set the KDBX backup password.")
					mnemonic := readMnemonicFromTTY()
					if !crypto.MnemonicValid(mnemonic) {
						fmt.Fprintln(os.Stderr, "❌ Invalid mnemonic checksum. Aborting backup.")
						os.Exit(1)
					}
					passphrase := crypto.MnemonicToPassphrase(mnemonic)
					kdfKey, kdfErr := crypto.Argon2idKey(passphrase, env.Slot1.Argon2Salt)
					if kdfErr != nil {
						fmt.Fprintf(os.Stderr, "❌ KDF error: %v\n", kdfErr)
						os.Exit(1)
					}
					backupPassword = fmt.Sprintf("%x", kdfKey)
					store.ZeroBytes(kdfKey)
				} else {
					_ = cfgDir
					backupPassword = promptKdbxPassword()
				}
			} else {
				_ = cfgDir
				backupPassword = promptKdbxPassword()
			}
		} else {
			backupPassword = promptKdbxPassword()
		}
	}

	absPath, err := filepath.Abs(outputFile)
	if err != nil {
		absPath = outputFile
	}

	err = backup.ExportToKdbx(absPath, backupPassword, storeSecrets)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Backup failed: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("[✓] Backup created at: %s\n", absPath)
	if explicitPassword == "" {
		fmt.Println("    KDBX password: your 24-word recovery mnemonic (Argon2id-derived).")
	}
}

func promptKdbxPassword() string {
	if !isInteractiveTerminal() {
		fmt.Fprintln(os.Stderr, "Error: cannot prompt for KDBX password in non-interactive mode. Use --custom-password.")
		os.Exit(1)
	}
	fmt.Print("Enter KeePassXC master password for backup: ")
	pass1, err := term.ReadPassword(int(syscall.Stdin))
	fmt.Println()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to read password: %v\n", err)
		os.Exit(1)
	}
	fmt.Print("Confirm KeePassXC master password: ")
	pass2, err2 := term.ReadPassword(int(syscall.Stdin))
	fmt.Println()
	if err2 != nil {
		fmt.Fprintf(os.Stderr, "Failed to read password: %v\n", err2)
		os.Exit(1)
	}
	if !bytes.Equal(pass1, pass2) {
		fmt.Fprintln(os.Stderr, "Error: Passwords do not match.")
		os.Exit(1)
	}
	return string(pass1)
}

func readMnemonicFromTTY() string {
	if !isInteractiveTerminal() {
		printInteractiveBlocker("sec-agent session recover", "Recovery mnemonic entry requires an interactive TTY to prevent scripts/agents from capturing seeds")
		os.Exit(78)
	}
	fmt.Print("Enter 24-word recovery mnemonic: ")
	reader := bufio.NewReader(os.Stdin)
	line, err := reader.ReadString('\n')
	if err != nil && err != io.EOF {
		fmt.Fprintf(os.Stderr, "\nFailed to read mnemonic: %v\n", err)
		os.Exit(1)
	}
	mnemonic := strings.TrimSpace(line)
	wordCount := len(strings.Fields(mnemonic))
	if wordCount != 24 {
		fmt.Fprintf(os.Stderr, "\n❌ Expected 24 words, got %d. Please re-enter the complete mnemonic.\n", wordCount)
		os.Exit(1)
	}
	return mnemonic
}

func handleMigrateV2(profile string, args []string) {
	dryRun := false
	forceReroll := false
	allProfiles := false
	seedInput := ""
	for i := 0; i < len(args); i++ {
		a := args[i]
		if a == "--help" || a == "-h" || a == "help" {
			if spec, ok := findCommandSpec("migrate-v2"); ok {
				printCommandHelp(spec)
			}
			return
		}
		if a == "--dry-run" {
			dryRun = true
		}
		if a == "--all-profiles" || a == "--all" {
			allProfiles = true
		}
		if a == "--force" || a == "--reroll" || a == "-f" {
			forceReroll = true
		}
		if a == "--seed" && i+1 < len(args) {
			seedInput = strings.Trim(args[i+1], `"'`)
			i++
		} else if strings.HasPrefix(a, "--seed=") {
			seedInput = strings.Trim(strings.TrimPrefix(a, "--seed="), `"'`)
		}
	}

	if seedInput != "" {
		if !crypto.MnemonicValid(seedInput) {
			fmt.Fprintln(os.Stderr, "❌ Provided seed phrase is not a valid 24-word BIP39 mnemonic.")
			os.Exit(1)
		}
	}

	if !dryRun && !isInteractiveTerminal() && seedInput == "" {
		cmdStr := "sec-agent migrate-v2"
		if profile != "default" && profile != "" {
			cmdStr += " --profile " + profile
		}
		if allProfiles {
			cmdStr += " --all-profiles"
		}
		printInteractiveBlocker(cmdStr, "Vault migration enrolls a 24-word recovery seed requiring physical human verification")
		os.Exit(78)
	}

	vaults, err := store.ListVaultFiles()
	if err != nil {
		fmt.Fprintf(os.Stderr, "❌ Failed to list vault files: %v\n", err)
		os.Exit(1)
	}
	if len(vaults) == 0 {
		fmt.Fprintln(os.Stderr, "❌ No vault files found. Run 'sec open' to initialize.")
		os.Exit(1)
	}

	var pending, alreadyV2 []store.VaultFileInfo
	for _, v := range vaults {
		if !allProfiles && profile != "default" && profile != "" && v.Profile != profile {
			continue
		}
		isCompleteV2 := v.IsV2 && v.HasSlot1
		if isCompleteV2 && !forceReroll && seedInput == "" {
			alreadyV2 = append(alreadyV2, v)
		} else {
			pending = append(pending, v)
		}
	}

	if dryRun {
		fmt.Println()
		fmt.Printf("Found %d vault file(s) in config directory:\n\n", len(vaults))
		for _, v := range vaults {
			if !allProfiles && profile != "default" && profile != "" && v.Profile != profile {
				continue
			}
			status := "⬜ v1.0 — would upgrade"
			if v.IsV2 {
				if v.HasSlot1 {
					status = "✅ v2.0 — Dual-Slot complete"
				} else {
					status = "⚠️  v2.0 — incomplete (Slot 1 missing)"
				}
			}
			fmt.Printf("  [%s]  profile=%-28s  %s\n", status, v.Profile, v.Path)
		}
		fmt.Printf("\nSummary: %d pending migration, %d already complete.\n", len(pending), len(alreadyV2))
		return
	}

	if len(pending) == 0 {
		fmt.Println("ℹ️  All vaults are already at v2.0 Dual-Slot format. Nothing to do.")
		return
	}

	mnemonic := seedInput
	if mnemonic == "" {
		if os.Getenv("SEC_TEST_MODE") != "1" {
			if !biometrics.Authenticate("Authorize v2.0 Dual-Slot Vault Migration") {
				fmt.Fprintln(os.Stderr, "❌ Touch ID biometric authorization required for vault migration.")
				os.Exit(1)
			}
		}
		m, err := crypto.GenerateMnemonic()
		if err != nil {
			fmt.Fprintf(os.Stderr, "❌ Failed to generate recovery mnemonic: %v\n", err)
			os.Exit(1)
		}
		mnemonic = m
	}

	words := strings.Fields(mnemonic)
	fmt.Println("🔑 Your 24-word recovery mnemonic (WRITE THIS DOWN NOW):")
	for i, w := range words {
		fmt.Printf("  %2d. %-12s", i+1, w)
		if (i+1)%4 == 0 {
			fmt.Println()
		}
	}
	fmt.Println()

	if seedInput == "" {
		fmt.Println("To confirm you have written down the mnemonic, please enter:")
		verificationWords := []int{4, 12, 20}
		for _, pos := range verificationWords {
			fmt.Printf("  Word #%d: ", pos)
			reader := bufio.NewReader(os.Stdin)
			entered, _ := reader.ReadString('\n')
			entered = strings.TrimSpace(strings.ToLower(entered))
			expected := strings.ToLower(words[pos-1])
			if entered != expected {
				fmt.Fprintf(os.Stderr, "\n❌ Word #%d mismatch (expected %q, got %q). Aborting.\n", pos, expected, entered)
				os.Exit(1)
			}
		}
	}

	if err := store.MigrateStageWrite("upgrading"); err != nil {
		fmt.Fprintf(os.Stderr, "❌ Failed to write migration stage marker: %v\n", err)
		os.Exit(1)
	}

	succeeded := 0
	for _, vaultInfo := range pending {
		kcSvc := "sec-session"
		if os.Getenv("SEC_TEST_MODE") == "1" {
			kcSvc = "sec-test-session"
		}
		if vaultInfo.Profile != "default" {
			if os.Getenv("SEC_TEST_MODE") == "1" {
				kcSvc = "sec-test-session:profile_" + vaultInfo.Profile
			} else {
				kcSvc = "sec-session:profile_" + vaultInfo.Profile
			}
		}
		kcAcc := "master"

		masterKey, mkErr := keychain.Get(kcSvc, kcAcc)
		if mkErr != nil || len(masterKey) == 0 {
			fmt.Fprintf(os.Stderr, "  ⚠️  Cannot access Keychain master key for profile %q: %v\n", vaultInfo.Profile, mkErr)
			fmt.Fprintf(os.Stderr, "     Run 'sec-agent --profile %s open' first, then re-run migration.\n", vaultInfo.Profile)
			continue
		}

		slot1, wrapErr := store.WrapMasterKey(mnemonic, masterKey)
		if wrapErr != nil {
			fmt.Fprintf(os.Stderr, "  ❌ Failed to wrap master key for profile %q: %v\n", vaultInfo.Profile, wrapErr)
			store.ZeroBytes(masterKey)
			continue
		}

		var rawPayload []byte
		if store.IsV2Vault(vaultInfo.Path) {
			existingEnv, readErr := store.ReadVaultEnvelope(vaultInfo.Path)
			if readErr != nil {
				fmt.Fprintf(os.Stderr, "  ❌ Failed to read vault envelope for profile %q: %v\n", vaultInfo.Profile, readErr)
				store.ZeroBytes(masterKey)
				continue
			}
			rawPayload = existingEnv.Payload
		} else {
			data, readErr := os.ReadFile(vaultInfo.Path) // #nosec G304
			if readErr != nil {
				fmt.Fprintf(os.Stderr, "  ❌ Failed to read vault file for profile %q: %v\n", vaultInfo.Profile, readErr)
				store.ZeroBytes(masterKey)
				continue
			}
			rawPayload = data
		}

		// Pre-flight validation: ensure masterKey from Keychain decrypts rawPayload
		if _, testErr := crypto.Decrypt(masterKey, rawPayload); testErr != nil {
			fmt.Fprintf(os.Stderr, "  ⚠️  Cannot load master key for profile %q: keychain key mismatch\n", vaultInfo.Profile)
			fmt.Fprintf(os.Stderr, "     This profile may require 'sec session recover --profile %s' first.\n", vaultInfo.Profile)
			store.ZeroBytes(masterKey)
			continue
		}

		env := &store.VaultEnvelope{
			SchemaVersion: store.SchemaV2,
			UpgradedAt:    time.Now().UTC(),
			Slot1:         slot1,
			Payload:       rawPayload,
		}
		if writeErr := store.WriteVaultEnvelope(vaultInfo.Path, env); writeErr != nil {
			fmt.Fprintf(os.Stderr, "  ❌ Failed to write vault envelope for profile %q: %v\n", vaultInfo.Profile, writeErr)
			store.ZeroBytes(masterKey)
			continue
		}

		_ = keychain.Set(kcSvc, kcAcc, masterKey)
		store.ZeroBytes(masterKey)
		evictStaleDaemon(vaultInfo.Profile)
		fmt.Printf("  ✅ Profile %-20s upgraded to v2.0 Dual-Slot format\n", vaultInfo.Profile)
		succeeded++
	}

	_ = store.MigrateStageRemove()
	if succeeded > 0 {
		fmt.Printf("\n✅ Successfully upgraded %d vault(s) to v2.0 Dual-Slot format.\n", succeeded)
	} else {
		fmt.Fprintln(os.Stderr, "\n❌ No vaults were upgraded. Review the warnings above.")
	}
}

func handleSessionRecover(profile string) {
	if !isInteractiveTerminal() {
		cmdStr := "sec-agent session recover"
		if profile != "default" && profile != "" {
			cmdStr += " --profile " + profile
		}
		printInteractiveBlocker(cmdStr, "Session recovery requires interactive TTY to enter recovery mnemonic")
		os.Exit(78)
	}

	vaultPath := store.GetStorePathForProfile(profile)
	if vaultPath == "" {
		fmt.Fprintln(os.Stderr, "❌ Failed to resolve vault path.")
		os.Exit(1)
	}

	if !store.IsV2Vault(vaultPath) {
		fmt.Fprintln(os.Stderr, "❌ Vault is not in v2.0 format. Recovery requires a migrated vault.")
		fmt.Fprintln(os.Stderr, "   Run 'sec migrate-v2' first to enroll a recovery mnemonic.")
		os.Exit(1)
	}

	env, err := store.ReadVaultEnvelope(vaultPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "❌ Failed to read vault envelope: %v\n", err)
		os.Exit(1)
	}

	if env.Slot1 == nil {
		fmt.Fprintln(os.Stderr, "❌ Vault has no Slot1 (BIP39) recovery key enrolled.")
		os.Exit(1)
	}

	fmt.Println()
	fmt.Println("╔═══════════════════════════════════════════════════════════════╗")
	fmt.Println("║       sec-agent Vault Recovery — BIP39 Mnemonic               ║")
	fmt.Println("╚═══════════════════════════════════════════════════════════════╝")
	fmt.Println()
	fmt.Println("You are about to recover vault access using your 24-word recovery mnemonic.")
	fmt.Println("After recovery, Touch ID will be re-bound to current system biometrics.")
	fmt.Println()
	fmt.Println("⚠️  SECURITY WARNING — VERIFY FINGERPRINTS FIRST:")
	fmt.Println("   • If Touch ID failed unexpectedly without you adding/removing a finger,")
	fmt.Println("     an administrator or attacker may have tampered with your system!")
	fmt.Println("   • Open macOS System Settings -> Touch ID & Passcode NOW.")
	fmt.Println("   • Ensure ONLY your authorized fingerprints are enrolled before proceeding.")
	fmt.Println("   • Remove any unrecognized fingerprints first!")
	fmt.Println()
	fmt.Println("Press Ctrl+C at any time to abort. No changes will be made until recovery succeeds.")
	fmt.Println()

	mnemonic := readMnemonicFromTTY()

	fmt.Println("\n⏳ Deriving recovery key (Argon2id, ~5 seconds)...")
	masterKey, err := store.UnwrapMasterKey(mnemonic, env.Slot1)
	if err != nil {
		fmt.Fprintf(os.Stderr, "\n❌ Recovery failed: %v\n", err)
		fmt.Fprintln(os.Stderr, "   Double-check each word carefully — BIP39 words are case-sensitive (all lowercase).")
		os.Exit(1)
	}
	defer store.ZeroBytes(masterKey)

	// Verify master key can decrypt the payload
	fmt.Println("✅ Mnemonic verified. Testing vault decryption...")
	_, decErr := store.LoadStore(profile, masterKey)
	if decErr != nil {
		fmt.Fprintf(os.Stderr, "❌ Vault decryption test failed: %v\n", decErr)
		fmt.Fprintln(os.Stderr, "   The mnemonic decrypted correctly but the vault payload could not be read.")
		fmt.Fprintln(os.Stderr, "   The vault file may be corrupted. Restore from a backup: 'sec restore <file.kdbx>'")
		os.Exit(1)
	}

	// Re-enroll the master key in Keychain with Touch ID BiometryCurrentSet protection
	kcSvc := "sec-session"
	if profile != "" && profile != "default" {
		kcSvc = "sec-session:profile_" + profile
	}
	kcAcc := "master"
	fmt.Println("🔑 Re-enrolling master key in macOS Keychain (Touch ID required)...")
	if err := keychain.Set(kcSvc, kcAcc, masterKey); err != nil {
		fmt.Fprintf(os.Stderr, "❌ Failed to re-enroll in Keychain: %v\n", err)
		os.Exit(1)
	}

	// Evict any stale background daemon for this profile to ensure fresh RAM cache on next open
	evictStaleDaemon(profile)

	fmt.Println()
	fmt.Println("╔═══════════════════════════════════════════════════════════════╗")
	fmt.Println("║  ✅  Vault recovery successful!                               ║")
	fmt.Println("╚═══════════════════════════════════════════════════════════════╝")
	fmt.Println()
	fmt.Println("Touch ID keychain entry has been restored.")
	fmt.Println("Run 'sec open' to start a new session.")
	fmt.Println()
	fmt.Println("📋 Security reminder:")
	fmt.Println("  • Your 24-word mnemonic remains valid for future recoveries.")
	fmt.Println("  • Store it safely — do NOT type it into any chat or script.")
}

func handleSession(profile string, args []string) {
	if len(args) > 0 && args[0] == "recover" {
		handleSessionRecover(profile)
		return
	}
	fmt.Fprintln(os.Stderr, "Usage: sec session recover")
	os.Exit(1)
}

func handleRestore(profile string, filePath string, args []string) {
	explicitPassword := ""
	for i := 0; i < len(args); i++ {
		if (args[i] == "-p" || args[i] == "--password") && i+1 < len(args) {
			explicitPassword = args[i+1]
			break
		}
	}
	handleRestoreFull(profile, filePath, explicitPassword, args)
}

func handleRestoreFull(profile string, filePath, explicitPassword string, args []string) {
	mergeMode := false
	overwriteMode := false
	fullMetadata := false
	for _, arg := range args {
		if arg == "--merge" || arg == "-m" {
			mergeMode = true
		} else if arg == "--overwrite" {
			overwriteMode = true
		} else if arg == "--full-metadata" {
			fullMetadata = true
		}
	}

	if strings.HasSuffix(filePath, ".enc") {
		cfgDir, err := config.GetConfigDir()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Restore error: %v\n", err)
			os.Exit(1)
		}
		targetPath := filepath.Join(cfgDir, "secrets.enc")
		if profile != "" && profile != "default" {
			targetPath = filepath.Join(cfgDir, fmt.Sprintf("secrets_%s.enc", profile))
		}
		// #nosec G304 G703
		data, err := os.ReadFile(filePath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to read snapshot file %s: %v\n", filePath, err)
			os.Exit(1)
		}
		// #nosec G304 G703
		if err := os.WriteFile(targetPath, data, 0600); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to overwrite vault database with snapshot: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("[✓] Restored snapshot %s to vault database -> %s\n", filePath, targetPath)
		return
	}

	var password string
	if explicitPassword != "" {
		password = explicitPassword
	} else {
		fmt.Print("Enter KeePassXC master password for restore: ")
		pass, err := term.ReadPassword(int(syscall.Stdin))
		fmt.Println()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to read password: %v\n", err)
			os.Exit(1)
		}
		password = string(pass)
	}

	var secrets map[store.SecretKey]store.SecretEntry
	var err error
	if filePath == "-" {
		if fullMetadata {
			rawSecrets, metaErr := backup.ImportFromKdbxFullMetadataReader(os.Stdin, password)
			err = metaErr
			if err == nil {
				secrets = make(map[store.SecretKey]store.SecretEntry, len(rawSecrets))
				for k, v := range rawSecrets {
					secrets[store.SecretKey(k)] = v
				}
			}
		} else {
			secrets, err = backup.ImportFromKdbxReader(os.Stdin, password)
		}
	} else {
		absPath, absErr := filepath.Abs(filePath)
		if absErr != nil {
			absPath = filePath
		}
		if fullMetadata {
			rawSecrets, metaErr := backup.ImportFromKdbxFullMetadata(absPath, password)
			err = metaErr
			if err == nil {
				secrets = make(map[store.SecretKey]store.SecretEntry, len(rawSecrets))
				for k, v := range rawSecrets {
					secrets[store.SecretKey(k)] = v
				}
			}
		} else {
			secrets, err = backup.ImportFromKdbx(absPath, password)
		}
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to restore backup: %v\n", err)
		os.Exit(1)
	}

	if mergeMode && !overwriteMode {
		curResp, err := queryDaemon(profile, daemon.IPCRequest{Action: daemon.IPCActionBackup})
		if err == nil && curResp.Success {
			filtered := make(map[store.SecretKey]store.SecretEntry)
			for k, v := range secrets {
				if _, exists := curResp.Secrets[string(k)]; !exists {
					filtered[k] = v
				}
			}
			secrets = filtered
		}
	}

	strSecrets := make(map[string]store.SecretEntry, len(secrets))
	for k, v := range secrets {
		strSecrets[string(k)] = v
	}

	resp, err := queryDaemon(profile, daemon.IPCRequest{
		Action:  daemon.IPCActionRestore,
		Secrets: strSecrets,
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error: Daemon is not running. Please run 'sec open' to unlock the session.")
		os.Exit(1)
	}

	if !resp.Success {
		fmt.Fprintf(os.Stderr, "Restore failed: %s\n", resp.Error)
		os.Exit(1)
	}

	fmt.Printf("Secrets restored successfully. Merged %d entries into active session.\n", len(secrets))
}

func handleSync(profile string, args []string) {
	if len(args) == 0 {
		fmt.Fprintln(os.Stderr, "Usage: sec sync export <file> | sec sync import <file>")
		os.Exit(1)
	}

	subCmd := args[0]
	switch subCmd {
	case "export":
		if len(args) < 2 {
			fmt.Fprintln(os.Stderr, "Usage: sec sync export <file.kdbx>")
			os.Exit(1)
		}
		outFile := args[1]
		checkProductionGuard(store.ProfileName(profile), args)
		handleBackup(profile, outFile, "")
	case "import":
		if len(args) < 2 {
			fmt.Fprintln(os.Stderr, "Usage: sec sync import <file.kdbx>")
			os.Exit(1)
		}
		inFile := args[1]
		handleRestore(profile, inFile, args[2:])
	default:
		fmt.Fprintf(os.Stderr, "Unknown sync action %q. Usage: sec sync export <file> | sec sync import <file>\n", subCmd)
		os.Exit(1)
	}
}

func handleMigrateLocal(profile string, dotenvPath string, args []string) {
	prefix := "env"
	for i := 0; i < len(args); i++ {
		if args[i] == "--prefix" {
			if i+1 < len(args) {
				prefix = args[i+1]
				i++
			} else {
				fail("INVALID_ARGUMENT", fmt.Errorf("flag --prefix requires a value"), "")
			}
		}
	}

	// #nosec G304 G703
	file, err := os.Open(dotenvPath)
	if err != nil {
		fail("FILE_READ_FAILED", err, "Verify that the dotenv file path is correct and accessible.")
	}
	defer file.Close()

	// Parse lines and modify in place
	type dotenvEntry struct {
		key      string
		rawLine  string
		isSecret bool
		value    string
	}
	var entries []dotenvEntry

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			entries = append(entries, dotenvEntry{rawLine: line})
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			entries = append(entries, dotenvEntry{rawLine: line})
			continue
		}

		k := strings.TrimSpace(parts[0])
		v := strings.TrimSpace(parts[1])

		// Strip quotes
		if (strings.HasPrefix(v, "\"") && strings.HasSuffix(v, "\"")) ||
			(strings.HasPrefix(v, "'") && strings.HasSuffix(v, "'")) {
			v = v[1 : len(v)-1]
		}

		// We assume it's a secret if it's not a common static config (e.g. PORT, NODE_ENV, etc.)
		if v != "" {
			entries = append(entries, dotenvEntry{
				key:      k,
				rawLine:  line,
				isSecret: true,
				value:    v,
			})
		} else {
			entries = append(entries, dotenvEntry{rawLine: line})
		}
	}

	if err := scanner.Err(); err != nil {
		fail("FILE_READ_FAILED", err, "")
	}

	// Connect to daemon to set the secrets
	importedCount := 0
	for _, entry := range entries {
		if !entry.isSecret {
			continue
		}

		// Determine path
		cleanKey := strings.ReplaceAll(strings.ToLower(entry.key), "_", "-")
		secretPath := cleanKey
		if prefix != "" {
			secretPath = prefix + "/" + cleanKey
		}

		resp, err := queryDaemon(profile, daemon.IPCRequest{
			Action: "set",
			Path:   secretPath,
			Value:  entry.value,
		})
		if err != nil {
			fail("DAEMON_NOT_RUNNING", fmt.Errorf("Daemon is not running. Please run 'sec open' to unlock the session."), "Run 'eval $(sec open)' to start/unlock the session.")
		}
		if !resp.Success {
			code, rem := mapDaemonError(resp.Error)
			fail(code, fmt.Errorf("failed to save key %q: %s", entry.key, resp.Error), rem)
		}
		importedCount++
	}

	// Write sanitized file back
	dir := filepath.Dir(dotenvPath)
	// #nosec G304 G703
	tmpFile, err := os.CreateTemp(dir, ".env.tmp.*")
	if err != nil {
		fail("FILE_WRITE_FAILED", err, "Verify permissions to write to target dotenv directory.")
	}
	tmpPath := tmpFile.Name()
	defer func() {
		_ = tmpFile.Close()
		// #nosec G304 G703
		_ = os.Remove(tmpPath)
	}()

	// Restrict permissions to owner-only
	if err := tmpFile.Chmod(0600); err != nil {
		fail("FILE_WRITE_FAILED", err, "")
	}

	writer := bufio.NewWriter(tmpFile)
	// Write a top header note
	if _, err := writer.WriteString(fmt.Sprintf("# Migrated to sec. Run your commands using: sec run --profile %s -- <command>\n", profile)); err != nil {
		fail("FILE_WRITE_FAILED", err, "")
	}

	for _, entry := range entries {
		var writeErr error
		if entry.isSecret {
			_, writeErr = writer.WriteString(fmt.Sprintf("%s=%q\n", entry.key, "<migrated_to_sec>"))
		} else {
			_, writeErr = writer.WriteString(entry.rawLine + "\n")
		}
		if writeErr != nil {
			fail("FILE_WRITE_FAILED", writeErr, "")
		}
	}
	if err := writer.Flush(); err != nil {
		fail("FILE_WRITE_FAILED", err, "")
	}

	// Force storage device sync (fsync)
	if err := tmpFile.Sync(); err != nil {
		fail("FILE_WRITE_FAILED", err, "")
	}

	if err := tmpFile.Close(); err != nil {
		fail("FILE_WRITE_FAILED", err, "")
	}

	// Atomically replace target dotenv file
	// #nosec G304 G703
	if err := os.Rename(tmpPath, dotenvPath); err != nil {
		fail("FILE_WRITE_FAILED", err, "Verify permissions to replace the target dotenv file.")
	}

	// Sync parent directory metadata
	// #nosec G304 G703
	dirFile, err := os.Open(dir)
	if err == nil {
		_ = dirFile.Sync()
		_ = dirFile.Close()
	}

	fmt.Printf("Successfully migrated %d secret(s) to sec (profile: %s). Dotenv file %q sanitized.\n", importedCount, profile, dotenvPath)
}
